# Project information
site_name: MLFlow - Introduction
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Section 01 Introduction to MLFlow: Section_001_MLFlow_Introduction.md
  - Section 02 MLFlow Tracking: Section_002_MLFlow_Tracking.md

site_author: Harshalkumar Gulabrao Kumre
site_description: >-
  This contains the introduction to MLFlow library

# Repository
repo_name: HARSHALKUMRE/mlflow-introduction
repo_url: https://github.com/HARSHALKUMRE/mlflow-introduction

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/HARSHALKUMRE/
    - icon: fontawesome/brands/twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/harshal-kumre/
    - icon: fontawesome/brands/instagram
      

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
  
  
plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/HARSHALKUMRE/"  target="_blank" rel="noopener">Harshalkumar Gulabrao Kumre</a>